
import java.awt.Color;

/**
 *
 * @author MasterWard
 */
public class Orange1 extends javax.swing.JPanel {

    // private String ans[] = {"Reverse", "Left", "Kia", "Reverse", "Right", "Reverse", "Left", "Reverse", "Reverse", "Reverse", "Reverse"}; // FOr debugging can delete later
    private int answer[] = {2, 4, 1, 3, 1, 2, 1, 3, 1, 4, 2, 1, 2, 3, 4, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2}; // Answers in int form
    private int selection[] = {0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7}; //  Things for the answers
    private int index = 0; // Index of answers on
    private String options[] = {" ", "Reverse", "Left", "Right", "Kia", "", "", ""}; // The options to choose
// This also means that 0 is nothing, 1 is reverse, 2 is left, 3 is right and 4 Kia in the selection array.

    /**
     * White belt Interactive Form
     */
    public Orange1() {
        initComponents();
    }

    /**
     * Method that deals with the painting of JTextFields based on selection and
     * answer arrays
     */
    private void paintingNew() {
        if (selection[index] == answer[index]) { // Moving on
            index++;
            selection[index] = 0; // Setting to yellow
        }
        /**
         * The First one is the Line\Question A=1, B=2, C=3, D=4, E=5 and so on;
         * The number is for the order of questions on that line. 1 is first 2
         * second, 3 is third and so on
         */
        
        A1.setText(options[selection[0]]);
        A1.setBackground(getColor(0));
        A2.setText(options[selection[1]]);
        A2.setBackground(getColor(1));
        A3.setText(options[selection[2]]);
        A3.setBackground(getColor(2));
        B1.setText(options[selection[3]]);
        B1.setBackground(getColor(3));
        B2.setText(options[selection[4]]);
        B2.setBackground(getColor(4));
        C1.setText(options[selection[5]]);
        C1.setBackground(getColor(5));
        C2.setText(options[selection[6]]);
        C2.setBackground(getColor(6));
        D1.setText(options[selection[7]]);
        D1.setBackground(getColor(7));
        D2.setText(options[selection[8]]);
        D2.setBackground(getColor(8));
        E1.setText(options[selection[9]]);
        E1.setBackground(getColor(9));
        F1.setText(options[selection[10]]);
        F1.setBackground(getColor(10));
        F2.setText(options[selection[11]]);
        F2.setBackground(getColor(11));
        F3.setText(options[selection[12]]);
        F3.setBackground(getColor(12));
        G1.setText(options[selection[13]]);
        G1.setBackground(getColor(13));
        G2.setText(options[selection[14]]);
        G2.setBackground(getColor(14));
        G3.setText(options[selection[15]]);
        G3.setBackground(getColor(15));
        H1.setText(options[selection[16]]);
        H1.setBackground(getColor(16));
        H2.setText(options[selection[17]]);
        H2.setBackground(getColor(17));
        H3.setText(options[selection[18]]);
        H3.setBackground(getColor(18));
        I1.setText(options[selection[19]]);
        I1.setBackground(getColor(19));
        I2.setText(options[selection[20]]);
        I2.setBackground(getColor(20));
        I3.setText(options[selection[21]]);
        I3.setBackground(getColor(21));
        I4.setText(options[selection[22]]);
        I4.setBackground(getColor(22));
        /* For debugging */
        //       System.out.println(Arrays.toString(answer));
        //     System.out.println(Arrays.toString(selection));
        //       System.out.println(index);
        /* For writting the JTextField code really quick */
 /*
        for (int i = 1; i < 29; i++) { // Used to write the part above this
            System.out.println("jTextField" + i + ".setText(options[selection[" + (i - 1) + "]]);");
            System.out.println("jTextField" + i + ".setBackground(getColor(" + (i - 1) + "));");
            System.out.print("0,"); // For the array
        }
         */

//        System.out.println("FUCK YOU BROKE IT. I AM NOT THERE YET");
    }

    /**
     * To decide what color each JTextField is going to be painted
     *
     * @param a
     * @return
     */
    private Color getColor(int a) {
        if (selection[a] == 7) {// Clear ones
            return (new Color(204, 204, 204));
        } else if (selection[a] == 0) { // Is the next one
            return Color.YELLOW;
        } else if (selection[a] == answer[a]) { // Right
            return Color.GREEN;
        } else { // Wrong
            return Color.RED;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reverse1 = new javax.swing.JButton();
        Left2 = new javax.swing.JButton();
        Right3 = new javax.swing.JButton();
        Kia4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        B2 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        D1 = new javax.swing.JTextField();
        B1 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        E1 = new javax.swing.JTextField();
        F1 = new javax.swing.JTextField();
        F2 = new javax.swing.JTextField();
        F3 = new javax.swing.JTextField();
        G1 = new javax.swing.JTextField();
        G2 = new javax.swing.JTextField();
        G3 = new javax.swing.JTextField();
        H1 = new javax.swing.JTextField();
        H2 = new javax.swing.JTextField();
        H3 = new javax.swing.JTextField();
        I1 = new javax.swing.JTextField();
        I2 = new javax.swing.JTextField();
        I3 = new javax.swing.JTextField();
        I4 = new javax.swing.JTextField();
        I5 = new javax.swing.JTextField();
        I6 = new javax.swing.JTextField();
        I7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1610, 910));
        setMinimumSize(new java.awt.Dimension(1610, 910));
        setName("White Belt"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1610, 910));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reverse1.setBackground(new java.awt.Color(0, 240, 240));
        Reverse1.setText("Reverse");
        Reverse1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Reverse1ItemStateChanged(evt);
            }
        });
        Reverse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reverse1MouseClicked(evt);
            }
        });
        Reverse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reverse1ActionPerformed(evt);
            }
        });
        add(Reverse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 68, 190, 45));

        Left2.setText("Left");
        Left2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Left2MouseClicked(evt);
            }
        });
        Left2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Left2ActionPerformed(evt);
            }
        });
        add(Left2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 68, 194, 45));

        Right3.setText("Right");
        Right3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Right3MouseClicked(evt);
            }
        });
        add(Right3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 68, 202, 45));

        Kia4.setText("Kia");
        Kia4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kia4MouseClicked(evt);
            }
        });
        add(Kia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 68, 145, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Word Bank");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 13, -1, -1));

        A1.setEditable(false);
        A1.setBackground(new java.awt.Color(204, 204, 204));
        A1.setText("Answer1");
        A1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        A1.setMaximumSize(new java.awt.Dimension(100, 100));
        A1.setMinimumSize(new java.awt.Dimension(10, 22));
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 204, 63, -1));

        A2.setEditable(false);
        A2.setBackground(new java.awt.Color(204, 204, 204));
        A2.setText("Answer2");
        A2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 204, 63, -1));

        A3.setEditable(false);
        A3.setBackground(new java.awt.Color(204, 204, 204));
        A3.setText("Answer3");
        A3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 204, 63, -1));

        B2.setEditable(false);
        B2.setBackground(new java.awt.Color(204, 204, 204));
        B2.setText("Answer5");
        B2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 249, 63, -1));

        C1.setEditable(false);
        C1.setBackground(new java.awt.Color(204, 204, 204));
        C1.setText("Answer6");
        C1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 248, 63, -1));

        C2.setEditable(false);
        C2.setBackground(new java.awt.Color(204, 204, 204));
        C2.setText("Answer7");
        C2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 248, 63, -1));

        D1.setEditable(false);
        D1.setBackground(new java.awt.Color(204, 204, 204));
        D1.setText("Answer8");
        D1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        D1.setVerifyInputWhenFocusTarget(false);
        add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 292, 63, -1));

        B1.setEditable(false);
        B1.setBackground(new java.awt.Color(204, 204, 204));
        B1.setText("Answer4");
        B1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 204, 63, -1));

        D2.setEditable(false);
        D2.setBackground(new java.awt.Color(204, 204, 204));
        D2.setText("Answer9");
        D2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 292, 63, -1));

        E1.setEditable(false);
        E1.setBackground(new java.awt.Color(204, 204, 204));
        E1.setText("Answer10");
        E1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1048, 315, 63, -1));

        F1.setEditable(false);
        F1.setBackground(new java.awt.Color(204, 204, 204));
        F1.setText("Answer11");
        F1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 336, 63, -1));

        F2.setEditable(false);
        F2.setBackground(new java.awt.Color(204, 204, 204));
        F2.setText("Answer12");
        F2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 336, 63, -1));

        F3.setEditable(false);
        F3.setBackground(new java.awt.Color(204, 204, 204));
        F3.setText("Answer13");
        F3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 358, 63, -1));

        G1.setEditable(false);
        G1.setBackground(new java.awt.Color(204, 204, 204));
        G1.setText("Answer14");
        G1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 380, 63, -1));

        G2.setEditable(false);
        G2.setBackground(new java.awt.Color(204, 204, 204));
        G2.setText("Answer15");
        G2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 63, -1));

        G3.setEditable(false);
        G3.setBackground(new java.awt.Color(204, 204, 204));
        G3.setText("Answer16");
        G3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 402, 63, -1));

        H1.setEditable(false);
        H1.setBackground(new java.awt.Color(204, 204, 204));
        H1.setText("Answer17");
        H1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 402, 63, -1));

        H2.setEditable(false);
        H2.setBackground(new java.awt.Color(204, 204, 204));
        H2.setText("Answer18");
        H2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 424, 63, -1));

        H3.setEditable(false);
        H3.setBackground(new java.awt.Color(204, 204, 204));
        H3.setText("Answer19");
        H3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 446, 63, -1));

        I1.setEditable(false);
        I1.setBackground(new java.awt.Color(204, 204, 204));
        I1.setText("Answer20");
        I1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 468, 63, -1));

        I2.setEditable(false);
        I2.setBackground(new java.awt.Color(204, 204, 204));
        I2.setText("Answer21");
        I2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 491, 63, -1));

        I3.setEditable(false);
        I3.setBackground(new java.awt.Color(204, 204, 204));
        I3.setText("Answer22");
        I3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 512, 63, -1));

        I4.setEditable(false);
        I4.setBackground(new java.awt.Color(204, 204, 204));
        I4.setText("Answer23");
        I4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 535, 63, -1));

        I5.setEditable(false);
        I5.setBackground(new java.awt.Color(204, 204, 204));
        I5.setText("Answer24");
        I5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I5, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 557, 63, -1));

        I6.setEditable(false);
        I6.setBackground(new java.awt.Color(204, 204, 204));
        I6.setText("Answer25");
        I6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        I6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I6ActionPerformed(evt);
            }
        });
        add(I6, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 580, 63, -1));

        I7.setEditable(false);
        I7.setBackground(new java.awt.Color(204, 204, 204));
        I7.setText("Answer26");
        I7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        I7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I7ActionPerformed(evt);
            }
        });
        add(I7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 602, 63, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1.           Block Into A           Side Fighting Stance Facing Your           And Say           .\n2. Point Forward, Step Forward Into A Forebalance, And Punch.\n3.           Block Into A           Side Fighting Stance Facing Your           .\n4. Point Forward, Step Forward Into A Forebalance, And Punch.\n5.           Block Into A           Side Forebalance Facing The Front.\n6. Point Forward, Step Forward And Punch, Step Forward And Punch Again, Step Forward And Punch A Third Time, Then Say           .\n7. Fold For A           Block, Spin 270 Degrees To Your Left, And Do A           Block.\n8. Point And Chamber, Step Forward Into A           Side Forebalance, And Punch.\n9. Do A           Block To The Other Side, Point And Chamber, Step Forward Into A           Side Forebalance, And Punch. \n10. Do A           Block To The Back In A           Side Forebalance.\n11. With The Same Hand You Did A Low Block With, Do A           Block.\n12. Step Forward And Do A Second           Block.\n13. Step Forward And Do A Third           Block.\n14. Step Forward And Do A Fourth           Block.\n15. Fold For A Chop, Spin 180 Degrees To Your Left, And Chop In A           Stance.\n16. Close Your Hand Into A Fist, Then Step Forward And Punch In A           Side Forebalance.\n17. Fold For A Chop, Spin 90 Degrees To Your Right, And Chop In A           Stance.\n18. Close Your Hand Into A Fist, Then Step Forward And Punch In A           Side Forebalance.\n19. Say           .\n");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 1510, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void Reverse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reverse1ActionPerformed

    }//GEN-LAST:event_Reverse1ActionPerformed

    private void Left2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Left2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Left2ActionPerformed

    private void Reverse1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Reverse1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Reverse1ItemStateChanged

    private void Reverse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reverse1MouseClicked
        //  System.out.println("Clicked reverse when the answer is " + ans[index]);
        selection[index] = 1;
        paintingNew();
    }//GEN-LAST:event_Reverse1MouseClicked

    private void Left2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Left2MouseClicked
        //  System.out.println("Clicked Left when the answer is " + ans[index]);
        selection[index] = 2;
        paintingNew();
    }//GEN-LAST:event_Left2MouseClicked

    private void Right3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Right3MouseClicked
        //    System.out.println("Clicked Right when the answer is " + ans[index]);
        selection[index] = 3;
        paintingNew();
    }//GEN-LAST:event_Right3MouseClicked

    private void Kia4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kia4MouseClicked
        //  System.out.println("Clicked Kia when the answer is " + ans[index]);
        selection[index] = 4;
        paintingNew();
    }//GEN-LAST:event_Kia4MouseClicked

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void I6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I6ActionPerformed

    private void I7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField E1;
    private javax.swing.JTextField F1;
    private javax.swing.JTextField F2;
    private javax.swing.JTextField F3;
    private javax.swing.JTextField G1;
    private javax.swing.JTextField G2;
    private javax.swing.JTextField G3;
    private javax.swing.JTextField H1;
    private javax.swing.JTextField H2;
    private javax.swing.JTextField H3;
    private javax.swing.JTextField I1;
    private javax.swing.JTextField I2;
    private javax.swing.JTextField I3;
    private javax.swing.JTextField I4;
    private javax.swing.JTextField I5;
    private javax.swing.JTextField I6;
    private javax.swing.JTextField I7;
    private javax.swing.JButton Kia4;
    private javax.swing.JButton Left2;
    private javax.swing.JButton Reverse1;
    private javax.swing.JButton Right3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
