
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MasterWard
 */
public class White1 extends javax.swing.JPanel {
    private int answer[] = {2, 4, 1, 3, 1, 2, 1, 3, 1, 4, 2, 6, 1, 3, 6, 1, 2, 6, 1, 3, 5, 6, 1, 2, 5, 6, 1, 3, 4}; // Answers in int form. These reflect the indices of the options array.
    private int selection = 0; // Variable that holds the player's response to a highlighted section of the text
    private int index = 0; // Index of answers on
    private String options[] = {" ", "Reverse", "Left", "Right", "Kia", "Slide-Up", "Front", ""}; // The options to choose
    private JTextField textFields[];
    public JFrame messages = new JFrame("JOptionPane showMessageDialog example");
    public Object messageoptions[] = {"Exit To Main Menu", "Quit Game"};

    /**
     * White belt Interactive Form
     */
    public White1() {
        initComponents();
        textFields = new JTextField[]{A1, A2, A3, B1, B2, C1, C2, D1, D2, E1, F1, F2, F3, G1, G2, G3, H1, H2, H3, I1, I2, I3, I4, J1, J2, J3, J4, K1, K2};
        initialPaint();
    }

    /**
     * Method that paints the first frame of the level
     */
    private void initialPaint()
    {
        // Erase the text from all text boxes
        for (int i = 0; i < answer.length; i++)
        {
            textFields[i].setText("");
        }
        
        // Paint the first text box yellow since we start there
        textFields[0].setBackground(Color.yellow);
    }
    
    /**
     * Method that deals with the painting of JTextFields based on selection and
     * answer arrays
     */
    private void paintingNew() {
        if (selection == answer[index]) // The player was correct, so let's move on
        {
            textFields[index].setText(options[answer[index]]);
            textFields[index].setBackground(Color.green); // Turn the previous highlight green
            index++;
            if (index == answer.length)
            {
                // Display a congratulatory text box here and ask the player if they want to return to the main menu or exit
                JOptionPane.showMessageDialog(null, "Congratulations, You Completed The Kata! Now Go Put These Steps Into Practce!");
                
                int choice = JOptionPane.showOptionDialog(null,
                        "Do You Want To Return To The Main Menu Or Exit The Game?",
                        "Next Steps", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, messageoptions, null);
                if (choice == 0)
                {
                    Main.display.DisplayMainMenu(false, true, false);
                }
                else
                {
                    // Kill all threads and exit
                    try
                    {
                        Main.display.kill();
                        JOptionPane.showMessageDialog(null, "Thanks For Playing!");
                        System.exit(0);
                    }
                    catch (Exception closeException)
                    {
                        JOptionPane.showMessageDialog(null, "Something Went Wrong When Attempting To Kill Program Threads. Force Closing Program.");
                        System.exit(0);
                    }
                }
            }
            else
                textFields[index].setBackground(Color.yellow); // Highlight the next text box yellow
        }
        else // The player was wrong
        {
            textFields[index].setBackground(Color.red); // Set the highlight color to red
            textFields[index].setText(options[selection]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reverse1 = new javax.swing.JButton();
        Left2 = new javax.swing.JButton();
        Right3 = new javax.swing.JButton();
        Kia4 = new javax.swing.JButton();
        Slide_Up5 = new javax.swing.JButton();
        Front6 = new javax.swing.JButton();
        MainMenuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        B1 = new javax.swing.JTextField();
        B2 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        D1 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        E1 = new javax.swing.JTextField();
        F1 = new javax.swing.JTextField();
        F2 = new javax.swing.JTextField();
        F3 = new javax.swing.JTextField();
        G1 = new javax.swing.JTextField();
        G2 = new javax.swing.JTextField();
        G3 = new javax.swing.JTextField();
        H1 = new javax.swing.JTextField();
        H2 = new javax.swing.JTextField();
        H3 = new javax.swing.JTextField();
        I1 = new javax.swing.JTextField();
        I2 = new javax.swing.JTextField();
        I3 = new javax.swing.JTextField();
        I4 = new javax.swing.JTextField();
        J1 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        K1 = new javax.swing.JTextField();
        K2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1610, 910));
        setMinimumSize(new java.awt.Dimension(1610, 910));
        setName("White Belt"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1610, 910));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reverse1.setBackground(new java.awt.Color(0, 240, 240));
        Reverse1.setText("Reverse");
        Reverse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reverse1MouseClicked(evt);
            }
        });
        add(Reverse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 60));

        Left2.setText("Left");
        Left2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Left2MouseClicked(evt);
            }
        });
        add(Left2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 190, 60));

        Right3.setText("Right");
        Right3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Right3MouseClicked(evt);
            }
        });
        add(Right3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 190, 60));

        Kia4.setText("Kia");
        Kia4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kia4MouseClicked(evt);
            }
        });
        add(Kia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 190, 60));

        Slide_Up5.setText("Slide-Up");
        Slide_Up5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide_Up5MouseClicked(evt);
            }
        });
        add(Slide_Up5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 190, 60));

        Front6.setText("Front");
        Front6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Front6MouseClicked(evt);
            }
        });
        add(Front6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 70, 190, 60));

        MainMenuButton.setText("Back To Main Menu");
        MainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuButtonMouseClicked(evt);
            }
        });
        add(MainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 855, 200, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Word Bank");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 90, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Steps For Kata Kee-Cho:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 160, 262, 40));

        A1.setEditable(false);
        A1.setBackground(new java.awt.Color(204, 204, 204));
        A1.setText("Answer1");
        A1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        A1.setMaximumSize(new java.awt.Dimension(100, 100));
        A1.setMinimumSize(new java.awt.Dimension(10, 22));
        add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 206, 63, -1));

        A2.setEditable(false);
        A2.setBackground(new java.awt.Color(204, 204, 204));
        A2.setText("Answer2");
        A2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        A2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 206, 63, -1));

        A3.setEditable(false);
        A3.setBackground(new java.awt.Color(204, 204, 204));
        A3.setText("Answer3");
        A3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 206, 63, -1));

        B1.setEditable(false);
        B1.setBackground(new java.awt.Color(204, 204, 204));
        B1.setText("Answer4");
        B1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 250, 63, -1));

        B2.setEditable(false);
        B2.setBackground(new java.awt.Color(204, 204, 204));
        B2.setText("Answer5");
        B2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 250, 63, -1));

        C1.setEditable(false);
        C1.setBackground(new java.awt.Color(204, 204, 204));
        C1.setText("Answer6");
        C1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 294, 63, -1));

        C2.setEditable(false);
        C2.setBackground(new java.awt.Color(204, 204, 204));
        C2.setText("Answer7");
        C2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 294, 56, -1));

        D1.setEditable(false);
        D1.setBackground(new java.awt.Color(204, 204, 204));
        D1.setText("Answer8");
        D1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 338, 63, -1));

        D2.setEditable(false);
        D2.setBackground(new java.awt.Color(204, 204, 204));
        D2.setText("Answer9");
        D2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 338, 56, -1));

        E1.setEditable(false);
        E1.setBackground(new java.awt.Color(204, 204, 204));
        E1.setText("Answer10");
        E1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 383, 63, -1));

        F1.setEditable(false);
        F1.setBackground(new java.awt.Color(204, 204, 204));
        F1.setText("Answer11");
        F1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 427, 63, -1));

        F2.setEditable(false);
        F2.setBackground(new java.awt.Color(204, 204, 204));
        F2.setText("Answer12");
        F2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 427, 63, -1));

        F3.setEditable(false);
        F3.setBackground(new java.awt.Color(204, 204, 204));
        F3.setText("Answer13");
        F3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 427, 63, -1));

        G1.setEditable(false);
        G1.setBackground(new java.awt.Color(204, 204, 204));
        G1.setText("Answer14");
        G1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 471, 63, -1));

        G2.setEditable(false);
        G2.setBackground(new java.awt.Color(204, 204, 204));
        G2.setText("Answer15");
        G2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 471, 63, -1));

        G3.setEditable(false);
        G3.setBackground(new java.awt.Color(204, 204, 204));
        G3.setText("Answer16");
        G3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 471, 63, -1));

        H1.setEditable(false);
        H1.setBackground(new java.awt.Color(204, 204, 204));
        H1.setText("Answer17");
        H1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 515, 63, -1));

        H2.setEditable(false);
        H2.setBackground(new java.awt.Color(204, 204, 204));
        H2.setText("Answer18");
        H2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 515, 63, -1));

        H3.setEditable(false);
        H3.setBackground(new java.awt.Color(204, 204, 204));
        H3.setText("Answer19");
        H3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 515, 63, -1));

        I1.setEditable(false);
        I1.setBackground(new java.awt.Color(204, 204, 204));
        I1.setText("Answer20");
        I1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 559, 63, -1));

        I2.setEditable(false);
        I2.setBackground(new java.awt.Color(204, 204, 204));
        I2.setText("Answer21");
        I2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 559, 63, -1));

        I3.setEditable(false);
        I3.setBackground(new java.awt.Color(204, 204, 204));
        I3.setText("Answer22");
        I3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 559, 63, -1));

        I4.setEditable(false);
        I4.setBackground(new java.awt.Color(204, 204, 204));
        I4.setText("Answer23");
        I4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 559, 63, -1));

        J1.setEditable(false);
        J1.setBackground(new java.awt.Color(204, 204, 204));
        J1.setText("Answer24");
        J1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 603, 63, -1));

        J2.setEditable(false);
        J2.setBackground(new java.awt.Color(204, 204, 204));
        J2.setText("Answer25");
        J2.setToolTipText("");
        J2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(J2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 603, 63, -1));

        J3.setEditable(false);
        J3.setBackground(new java.awt.Color(204, 204, 204));
        J3.setText("Answer26");
        J3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(J3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 603, 63, -1));

        J4.setEditable(false);
        J4.setBackground(new java.awt.Color(204, 204, 204));
        J4.setText("Answer27");
        J4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(J4, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 603, 63, -1));

        K1.setEditable(false);
        K1.setBackground(new java.awt.Color(204, 204, 204));
        K1.setText("Answer28");
        K1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 648, 63, -1));

        K2.setEditable(false);
        K2.setBackground(new java.awt.Color(204, 204, 204));
        K2.setText("Answer29");
        K2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        add(K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 648, 63, -1));

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Step into A            Side Fighting stance facing your left, Say            And Do A            Punch\n\n2. Step into A            Side Fighting Stance Facing Your Right And Do A            Punch.\n\n3. Step Into A            Side Fighting Stance Facing The Front And Do A          Punch.\n\n4. Step Into A            Side Fighting Stance Facing The Back And Do a          Punch.\n\n5. Say            After the Reverse Punch\n\n6. Step Into a            Side Fighting Stance Facing Your Left, do a            Kick, then a            Punch.\n\n7. Step Into a            Side Fighting Stance Facing Your Right, do a           Kick, Then A            Punch.\n\n8. Step Into a            Side Fighting Stance Facing The Back, Do A            Kick, Then A           Punch.\n\n9. Step Into a            Side Fighting Stance Facing The Front, Do A                       Kick, Then A            Punch.\n\n10. Step Into a            Side Fighting Stance Facing The Back, Do A                      Kick, Then A           Punch.\n\n11. Step Into a            Side Fighting Stance Facing The Front And Say           .");
        jTextArea1.setMinimumSize(new java.awt.Dimension(1400, 466));
        jTextArea1.setPreferredSize(new java.awt.Dimension(1400, 466));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 1510, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void Reverse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reverse1MouseClicked
        selection = 1;
        paintingNew();
    }//GEN-LAST:event_Reverse1MouseClicked

    private void Left2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Left2MouseClicked
        selection = 2;
        paintingNew();
    }//GEN-LAST:event_Left2MouseClicked

    private void Right3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Right3MouseClicked
        selection = 3;
        paintingNew();
    }//GEN-LAST:event_Right3MouseClicked

    private void Kia4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kia4MouseClicked
        selection = 4;
        paintingNew();
    }//GEN-LAST:event_Kia4MouseClicked

    private void Slide_Up5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide_Up5MouseClicked
        selection = 5;
        paintingNew();
    }//GEN-LAST:event_Slide_Up5MouseClicked

    private void Front6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Front6MouseClicked
        selection = 6;
        paintingNew();
    }//GEN-LAST:event_Front6MouseClicked

    private void MainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuButtonMouseClicked
        int confirm = JOptionPane.showOptionDialog(null,
                        "Are You Sure You Want To Return To The Main Menu? You Will Lose All Progress.",
                        "Exit Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == 0)
        {
            Main.display.DisplayMainMenu(false, true, false);
        }
    }//GEN-LAST:event_MainMenuButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField E1;
    private javax.swing.JTextField F1;
    private javax.swing.JTextField F2;
    private javax.swing.JTextField F3;
    private javax.swing.JButton Front6;
    private javax.swing.JTextField G1;
    private javax.swing.JTextField G2;
    private javax.swing.JTextField G3;
    private javax.swing.JTextField H1;
    private javax.swing.JTextField H2;
    private javax.swing.JTextField H3;
    private javax.swing.JTextField I1;
    private javax.swing.JTextField I2;
    private javax.swing.JTextField I3;
    private javax.swing.JTextField I4;
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JTextField K1;
    private javax.swing.JTextField K2;
    private javax.swing.JButton Kia4;
    private javax.swing.JButton Left2;
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JButton Reverse1;
    private javax.swing.JButton Right3;
    private javax.swing.JButton Slide_Up5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
